name: Unit tests pipeline

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Retrieving code from the repo using GitHub Actions

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.0-rc.1'  # Using v13 in this class

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest pytest-cov
      - name: Run tests
        # Calculates code coverage for myfile.py
        
        run: |
          pytest --cov=myfile
      
        env:
          CI: true
